// Parity layer (test plan §P): the ported engine must reproduce reference/golden.json,
// which was generated by the real the original Dart engine. Tolerance 1e-4.
import { assert, assertAlmostEquals, assertEquals } from "@std/assert";
import golden from "../reference/golden.json" with { type: "json" };
import {
  calculateAdvancedPnl,
  calculateCpaMatrix,
  calculatePlTracker,
  calculateReverseKpi,
  calculateUltimatePricing,
  type PricingResults,
  type PricingVariables,
} from "../engine/parity.ts";

const TOL = 1e-4;

type GoldenMode = keyof typeof golden;
type Row = Record<string, number | string | boolean>;

const CORE_FIELDS = [
  "totalCostPerUnit",
  "suggestedPrice",
  "breakevenPrice",
  "netProfit",
  "netMarginPct",
  "grossProfit",
  "maxCpa",
  "breakEvenRoas",
  "successRatePct",
  "leadsPerDelivered",
  "adCostPerDelivered",
  "blendedShipping",
  "operationsCost",
  "leadProcessingCost",
  "fixedCostsPerDelivered",
  "pctStack",
] as const;

interface ModeSpec {
  run: (v: PricingVariables) => PricingResults;
  extras: string[];
  lists: Record<string, number>;
}

const MODES: Record<GoldenMode, ModeSpec> = {
  cpaMatrix: { run: calculateCpaMatrix, extras: [], lists: { cpaMatrixRows: 8 } },
  reverseCalc: {
    run: calculateReverseKpi,
    extras: ["requiredPrice", "requiredCr", "breakevenMaxCpa", "survivalCr"],
    lists: { bundles: 18 },
  },
  advancedPnl: {
    run: calculateAdvancedPnl,
    extras: ["expectedPnl", "targetPnl", "breakevenPnl"],
    lists: { bundles: 3 },
  },
  ultimatePricing: {
    run: calculateUltimatePricing,
    extras: [],
    lists: { bundles: 3, cogsBreakdown: 7 },
  },
  plTracker: {
    run: calculatePlTracker,
    extras: ["revenue", "totalCogs", "actualCpa", "cpl", "crPct", "drPct", "roas", "rtoCount"],
    lists: { cogsBreakdown: 10 },
  },
};

/** Golden uses `successRatePct`; the engine keeps the original app's `successRate` (already ×100). */
function flatten(r: PricingResults): Record<string, unknown> {
  return { ...r, successRatePct: r.successRate };
}

function assertRowsMatch(field: string, actual: Row[], expected: Row[]) {
  assertEquals(actual.length, expected.length, `${field} length`);
  expected.forEach((exp, i) => {
    for (const [k, want] of Object.entries(exp)) {
      const got = actual[i][k];
      if (typeof want === "number") {
        assertAlmostEquals(got as number, want, TOL, `${field}[${i}].${k}`);
      } else {
        assertEquals(got, want, `${field}[${i}].${k}`);
      }
    }
  });
}

for (const mode of Object.keys(MODES) as GoldenMode[]) {
  Deno.test(`parity: ${mode} matches golden`, () => {
    const spec = MODES[mode];
    const { input, output } = golden[mode] as {
      input: PricingVariables;
      output: Record<string, unknown>;
    };
    const actual = flatten(spec.run(input));

    for (const f of [...CORE_FIELDS, ...spec.extras]) {
      assert(f in output, `golden has ${f}`);
      assertAlmostEquals(actual[f] as number, output[f] as number, TOL, `${mode}.${f}`);
    }
    for (const [list, len] of Object.entries(spec.lists)) {
      const expected = output[list] as Row[];
      assertEquals(expected.length, len, `golden ${list} length`);
      assertRowsMatch(`${mode}.${list}`, actual[list] as Row[], expected);
    }
  });
}

Deno.test("parity: ultimate anchors (guards against a broken loader)", () => {
  const r = calculateUltimatePricing(golden.ultimatePricing.input as PricingVariables);
  assertAlmostEquals(r.suggestedPrice, 345.2273, TOL);
  assertAlmostEquals(r.breakevenPrice, 296.9438, TOL);
  assertAlmostEquals(r.netProfit, 34.5227, TOL);
  assertAlmostEquals(r.netMarginPct, 10.0, TOL);
  assertAlmostEquals(r.maxCpa, 24.3211, TOL);
  assertAlmostEquals(r.breakEvenRoas, 3.8325, TOL);
  assertAlmostEquals(r.pctStack, 0.285, TOL);
  assertAlmostEquals(r.leadProcessingCost, 9.2593, TOL);
});

Deno.test("parity T9: tracker success rate comes from input CR/DR, not actual counts", () => {
  const input = { ...golden.plTracker.input, confirmationRatePct: 60, deliveryRatePct: 45 };
  const r = calculatePlTracker(input as PricingVariables);
  assertAlmostEquals(r.successRate, 27.0, TOL);
  assertAlmostEquals(r.leadsPerDelivered, 3.7037, TOL);
  assertAlmostEquals(r.crPct, 50, TOL);
  assertAlmostEquals(r.drPct, 80, TOL);
});

Deno.test("parity E1/E2: CR = 0 or DR = 0 silently drops ad cost (the original app behaviour)", () => {
  const base = golden.ultimatePricing.input as PricingVariables;
  for (const zero of [{ confirmationRatePct: 0 }, { deliveryRatePct: 0 }]) {
    const r = calculateUltimatePricing({ ...base, ...zero });
    assertEquals(r.leadsPerDelivered, 0);
    assertEquals(r.adCostPerDelivered, 0);
    assert(Number.isFinite(r.suggestedPrice));
  }
  const dr0 = calculateUltimatePricing({ ...base, deliveryRatePct: 0 });
  assertEquals(dr0.blendedShipping, base.returnShippingFee);
});

Deno.test("parity E3/E4: stack + margin ≥ 100% returns 0, not Infinity", () => {
  const base = golden.ultimatePricing.input as PricingVariables;
  const r = calculateUltimatePricing({
    ...base,
    vatPct: 80,
    platformFeePct: 0,
    marketerCommissionPct: 0,
    paymentGatewayPct: 0,
    targetMarginPct: 20,
  });
  assertEquals(r.suggestedPrice, 0);
  assert(Number.isFinite(r.breakevenPrice) && r.breakevenPrice > 0);
  const over = calculateUltimatePricing({ ...base, vatPct: 100 });
  assertEquals(over.breakevenPrice, 0);
  assertEquals(over.suggestedPrice, 0);
});

Deno.test("parity E6: empty campaign yields zeros, never NaN", () => {
  const r = calculatePlTracker({
    ...golden.plTracker.input,
    adSpend: 0,
    totalLeads: 0,
    confirmedOrders: 0,
    deliveredOrders: 0,
  } as PricingVariables);
  for (const [k, v] of Object.entries(r)) {
    if (typeof v === "number") assert(Number.isFinite(v), `${k} is finite`);
  }
  assertEquals(r.revenue, 0);
  assertEquals(r.roas, 0);
  assertEquals(r.breakEvenRoas, 0);
});
